export const SITE = {
  name: 'Hartwell & Stone',
  legalName: 'Hartwell & Stone Construction Ltd',
  tagline: 'Building Excellence Since 1987',
  description: 'Premium residential construction in Essex. Extensions, loft conversions, renovations and new builds. FMB registered, 38 years of excellence.',
  url: 'https://hartwell-stone.pages.dev',
  phone: '01245 267 891',
  email: 'info@hartwellandstone.co.uk',
  whatsapp: '441245267891',
  address: {
    street: '14 Duke Street',
    area: 'Chelmsford',
    city: 'Essex',
    postcode: 'CM1 1HL',
    country: 'GB',
  },
  hours: {
    weekday: 'Mon–Fri: 7:30am – 5:30pm',
    saturday: 'Sat: 8:00am – 1:00pm',
    sunday: 'Sun: Closed',
  },
  founded: 1987,
  yearsExperience: new Date().getFullYear() - 1987,
  projects: '500+',
  satisfaction: '98%',
  awards: '50+',
  reviews: { count: 127, rating: 4.9 },
  accreditations: {
    fmb: 'FMB Member No. 48291',
    trustmark: 'TrustMark Reg. TM39841',
    checkatrade: 'Checkatrade Verified',
    labc: 'LABC Partner',
    trustedTrader: 'Which? Trusted Trader',
  },
  social: {
    facebook: 'https://facebook.com/hartwellandstone',
    instagram: 'https://instagram.com/hartwellandstone',
  },
};
