export const SITE = {
  name: 'Hartwell & Stone',
  legalName: 'Hartwell & Stone Construction Ltd',
  tagline: 'Building Britain\'s Finest Homes Since 1987',
  description: 'Award-winning residential construction, heritage restoration and bespoke new builds. From elegant extensions to listed building renovations, Hartwell & Stone delivers craftsmanship without compromise across the South East and nationwide by arrangement. FMB registered, LABC award-winning, 37 years of excellence.',
  url: 'https://hartwell-stone.pages.dev',
  phone: '01245 267 891',
  email: 'info@hartwellandstone.co.uk',
  whatsapp: '441245267891',
  address: {
    street: '14 Duke Street',
    area: 'Chelmsford',
    city: 'Essex',
    postcode: 'CM1 1HL',
    country: 'GB',
  },
  hours: {
    weekday: 'Mon–Fri: 7:30am – 5:30pm',
    saturday: 'Sat: 8:00am – 1:00pm',
    sunday: 'Sun: Closed',
  },
  founded: 1987,
  yearsExperience: new Date().getFullYear() - 1987,
  projects: '487',
  satisfaction: '98.4%',
  awards: '34',
  reviews: { count: 143, rating: 4.9 },
  companyNumber: '02841967',
  vatNumber: 'GB 421 7839 12',
  numberOfEmployees: '45+',
  accreditations: {
    fmb: 'FMB Member No. 48291',
    trustmark: 'TrustMark Reg. TM39841',
    checkatrade: 'Checkatrade Verified',
    labc: 'LABC Registered Partner',
    trustedTrader: 'Which? Trusted Trader',
    nhbc: 'NHBC Registered Builder',
  },
  social: {
    facebook: 'https://facebook.com/hartwellandstone',
    instagram: 'https://instagram.com/hartwellandstone',
  },
};
